config/routes.rb
Legekontor::Application.routes.draw do
   root to: 'pages#home'
  resources :kirurgis, :types, :infos
  

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :content, :name, :type_id
  belongs_to :type
  
end

app/models/kirurgi.rb
class Kirurgi < ActiveRecord::Base
  attr_accessible :name, :types_attributes
  has_many :types
  accepts_nested_attributes_for :types, allow_destroy: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :title, :content, :kirurgi_id, :infos_attributes
  belongs_to :kirurgi
  has_many :infos
  accepts_nested_attributes_for :infos, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def show
    @info = Info.find(params[:id])
  end
end

app/controllers/kirurgis_controller.rb
class KirurgisController < ApplicationController
  # GET /kirurgis
  # GET /kirurgis.json
  def index
    @kirurgis = Kirurgi.all
  end

  def show
    @kirurgi = Kirurgi.find(params[:id])
  end

  def new
    @kirurgi = Kirurgi.new
  end

  def edit
    @kirurgi = Kirurgi.find(params[:id])
  end

  def create
    @kirurgi = Kirurgi.new(params[:kirurgi])

    
      if @kirurgi.save
        redirect_to @kirurgi, notice: "Successfully created"
     else
       render :new

    end
  end

  def update
    @kirurgi = Kirurgi.find(params[:id])

    
      if @kirurgi.update_attributes(params[:kirurgi])
        redirect_to @kirurgi, notice: "Successfully created"
      else
        render :edit
        
    end
  end

  def destroy
    @kirurgi = Kirurgi.find(params[:id])
    @kirurgi.destroy
    redirect_to kirurgis_url, notice: "Successfully deleted"
   
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  
  def show
    @type = Type.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/kirurgis_helper.rb
module KirurgisHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/infos/show.html.erb
<h1><%= @info.name %></h1>

<%= simple_format @info.content %>

app/views/kirurgis/_form.html.erb
<%= form_for(@kirurgi) do |f| %>
  <% if @kirurgi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kirurgi.errors.count, "error") %> prohibited this kirurgi from being saved:</h2>

      <ul>
      <% @kirurgi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Navn paa hoved type kirurgi:" %><br />
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :types do |builder| %>
  
  	<%= render 'type_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Legg til type", f, :types %>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kirurgis/_info_fields.html.erb
<fieldset>
  <%= f.label :name, "Navn paa link" %><br />
  <%= f.text_field :name %>
  <%= f.hidden_field :_destroy %><br/>
  <%= f.label :content, "Info for denne siden" %><br />
  <%= f.text_area :content, :cols => 40, :rows => 15, :class => "widgEditor" %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Slett", '#', class: "remove_fields" %>
</fieldset>

app/views/kirurgis/_type_fields.html.erb
<fieldset>
  <%= f.label :title, "Tittel" %><br />
  <%= f.text_field :title %><br />
  <%= f.label :content, "Hvilken type kirurgi:" %><br />
  <%= f.text_area :content, :cols => 40, :rows => 15, :class => "widgEditor" %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Slett denne" %>
  <%= f.fields_for :infos do |builder| %>
    <%= render 'info_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Legg til info for denne typen", f, :infos %>
</fieldset>

app/views/kirurgis/edit.html.erb
<h1>Rediger Plastisk Kirurgi</h1>

<%= render 'form' %>
<div class="buttonLinks">
<%= link_to 'Show', @kirurgi %>
<%= link_to 'Back', kirurgis_path %>
</div>

app/views/kirurgis/index.html.erb
<h1>Listing kirurgis</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kirurgis.each do |kirurgi| %>
  <tr>
    <td><%= kirurgi.name %></td>
    <td><%= link_to 'Show', kirurgi %></td>
    <td><%= link_to 'Edit', edit_kirurgi_path(kirurgi) %></td>
    <td><%= link_to 'Destroy', kirurgi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kirurgi', new_kirurgi_path %>

app/views/kirurgis/new.html.erb
<h1>Ny Oppforing i Plastisk Kirurgi menyen</h1>

<%= render 'form' %>
<div class="buttonLinks">
<%= link_to 'Back', kirurgis_path %>
</div>

app/views/kirurgis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @kirurgi.name %>
</p>


<%= link_to 'Edit', edit_kirurgi_path(@kirurgi) %> |
<%= link_to 'Back', kirurgis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Legekontor</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<script>
			function showstuff(boxid, i) {
				var s = document.getElementById(boxid);
				if(s.style.display == 'none' && i == 0) {
					s.style.display = "block";
					return false;
				} else {
					s.style.display = "none";
					return false;
				} 

			}
		</script>
		<body>
			<header>
				<div id="logo">
				<!--<img class="logo" src="http://www.seeklogo.com/images/D/Doctor_Design-logo-CCE6ADC5A3-seeklogo.com.gif" alt="Logo"/>-->
				<img class="headerpic" src="http://www.miltonhilton.com/blog/uploaded_images/ID_doctor_logo_96-742859.jpg" alt="pic"/>
				</div>
			</header>
			<nav>
				<%= link_to 'Home', root_path, :class => 'home' %> 
				<a href="javascript:void(0)" onclick="showstuff('show', 0);"> Kirurgi</a>
			
			<div  id="show" class="hidden">
				<% if Kirurgi.find(:all).count > 0 %>

				<% Kirurgi.find(:all, :order => 'name ASC').each do |k| %>
				<div id="leftNav">
					<h1><%= k.name %></h1>
					<% k.types.each do |t|%>
					<p>
						<%= link_to t.title, t %>
					</p>
					<%end%>
				</div>
				<% end %>
				<% end %>
			</div>
			</nav>
			<%= yield %>
				
			
				<h1 class="contactus">Kontakt oss</h1>
			<footer></footer>
		</body>
</html>

app/views/pages/home.html.erb
<section onclick="showstuff('show', 1);" id="photos">
				<div class="wrapper">
			<div id="slideshow">
						<img src="http://miriadna.com/desctopwalls/images/max/Autumn-trees.jpg">
						
					</div>
				</div>
			</section>
			<section onclick="showstuff('show', 1);"  id="statement">
				<div class="wrapper nobottom">
							<p>
			Plastisk kirurgi gir deg mange valgmuligheter. Har du et konkret problem du ønsker å forandre, kan synlige forbedringer ofte oppnås med plastisk kirurgi. Vi tilbyr et bredt spekter av operasjoner både i ansikt og på kropp. Vi har 25 års erfaring og høy medisinsk kompetanse. Det er viktig for oss å oppnå et godt resultat og at du skal føle deg trygg. I samarbeid med Klinikk Bunæs i Sandvika, tilbyr vi et komplett tilbud innenfor kosmetiske behandlinger og plastisk kirurgi.  
					</p>
				
				</div>
				
</section>

app/views/types/show.html.erb
<h1><%= @type.title %></h1>

<p><%= @type.content %></p>

<% @type.infos.each do |i|%>
	
	<p><%= link_to i.name, i %></p>

<% end %>